### ISSUE TITLE
validateRequestParams interface

### ISSUE THREAD

**Issue by kosecki123** [ethereum-alarm-clock/eac.js-client#31]
Update when https://github.com/ethereum-alarm-clock/ethereum-alarm-clock/pull/141 merged and deployed.

**Comment by adibas03** [comment]
Implemented
https://github.com/ethereum-alarm-clock/eac.js-lib/commit/b763f135626ed831d9cd6a0583cf26f914ef40ad
https://github.com/ethereum-alarm-clock/eac.js-lib/commit/df354f1d1115a34e8c2844e4563d05d638b9cb52
