### ISSUE TITLE
Mutex breaks on wallet

### ISSUE THREAD

**Issue by lsaether** [ethereum-alarm-clock/eac.js-client#99]
This may be something else but reporting it anyway.

As I'm testing with CLI I notice that if there's a large volume of transactions that a TimeNode needs to send, the mutex breaks and gets stuck on `account X is sending transaction` even if theres no transaction which is being sent.

**Comment by Kuzirashi** [comment]
One of the potential solutions (or I'd say workarounds) could be timer which sets the `isSendingTransaction` flag back to `false`, when it takes more than 60 seconds. 60 is an arbitrary number.

**Comment by lsaether** [comment]
The change I made locally was to change the `throw Error` to logging output since I think the error throwing caused the program to halt and the `finally` block doesn't run. Not sure if this was it, but it seems to be working now. The clock idea is good as well.
